name: snail
description: A Simple ORM-like Library for Flutter/Dart.
version: 1.0.0
homepage: https://github.com/evandersondev/snail

environment:
  sdk: ">=3.6.0 <4.0.0"

platforms:
  android:
  ios:
  macos:

# Add regular dependencies here.
dependencies:
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
