name: snail
description: A library inspired by Spring Boot's JPA that facilitates SQLite database management in Flutter/Dart applications.
version: 1.0.1
homepage: https://github.com/evandersondev/snail

environment:
  sdk: ^3.6.0

platforms:
  android:
  ios:
  macos:

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
